questions = {
    "Capital of Great Britain?": "London",
    "What year was Apple founded?": "1976",
    "The largest lake in the world?": "Caspian Sea",
    "How many states are there in the USA (2024)?": "50",
    "Capital of Italy?": "Rome",
    "What is the highest mountain in the world?": "Everest",
    "The hottest continent on Earth?": "Africa",
    "The longest river in the world?": "Amazon",
    "What is the name of the science of numbers and their properties?": "Mathematics",
    "Capital of France?": "Paris",
    "How many continents are there on Earth?": "7",
    "What is the name of the unit of gravity?": "Newton",
    "What is the national dish of Japan?": "Sushi",
    "What is the name of the tallest building in the world?": "Burj Khalifa",
    "How many vowels are there in the Russian alphabet?": "10",
    "Which chemical element has the symbol H?": "Hydrogen",
    "The largest ocean in the world?": "Pacific Ocean",
    "Capital of Germany?": "Berlin",
    "Who painted the Mona Lisa?": "Leonardo da Vinci",
    "What is the smallest country in the world?": "Vatican City",
    "How many planets are in the Solar System (2024)?": "8",
    "The fastest land animal?": "Cheetah",
    "The hardest natural substance on Earth?": "Diamond",
    "What is the capital of Spain?": "Madrid",
    "Who wrote 'Romeo and Juliet'?": "William Shakespeare",
    "The longest bone in the human body?": "Femur",
    "Which planet is known as the Red Planet?": "Mars",
    "What is the square root of 64?": "8",
    "Which gas do plants absorb from the atmosphere?": "Carbon dioxide",
    "The most spoken language in the world?": "English",
    "What is the boiling point of water at sea level (°C)?": "100",
    "What is the national animal of India?": "Tiger",
    "How many sides does a hexagon have?": "6",
    "Who invented the light bulb?": "Thomas Edison",
    "The largest desert in the world?": "Sahara",
    "The chemical formula for water?": "H2O",
    "What is the capital of Canada?": "Ottawa",
    "Which element has the atomic number 1?": "Hydrogen",
    "The fastest bird in the world?": "Peregrine Falcon",
    "What is the capital of Brazil?": "Brasilia",
    "What is the main ingredient in bread?": "Flour",
    "Which sport is known as 'the beautiful game'?": "Football (Soccer)",
    "What is the tallest animal in the world?": "Giraffe",
    "What is the name of the longest reigning British monarch?": "Queen Elizabeth II",
    "What is the capital of Russia?": "Moscow",
    "What is the largest mammal on Earth?": "Blue Whale",
    "What is the name of the galaxy we live in?": "Milky Way",
    "What is the speed of light in a vacuum (m/s)?": "299792458",
    "Which ocean is located at the North Pole?": "Arctic Ocean",
    "What is the smallest unit of life?": "Cell",
    "What is the name of the largest rainforest in the world?": "Amazon Rainforest",
    "Who developed the theory of relativity?": "Albert Einstein",
    "What is the name of the Roman god of war?": "Mars",
    "Which country is known as the Land of the Rising Sun?": "Japan",
    "How many stripes are on the American flag?": "13",
    "What is the primary gas in Earth's atmosphere?": "Nitrogen",
    "What is the chemical symbol for gold?": "Au",
    "What is the largest island in the world?": "Greenland",
    "What is the name of the Greek goddess of wisdom?": "Athena",
    "Which country has the most natural lakes?": "Canada",
    "What is the capital of Australia?": "Canberra",
    "What is the smallest prime number?": "2",
    "Which instrument has 88 keys?": "Piano",
    "What is the most abundant element in the universe?": "Hydrogen",
    "Who is known as the father of computers?": "Charles Babbage",
    "What is the longest highway in the world?": "Pan-American Highway",
    "What is the study of plants called?": "Botany",
    "What is the capital of Egypt?": "Cairo",
    "What is the coldest planet in the Solar System?": "Uranus",
    "What is the largest bone in the human body?": "Femur",
    "What is the most populous country in the world?": "China",
    "Which organ purifies blood in the human body?": "Kidneys",
    "What is the main currency used in Japan?": "Yen",
    "What is the hardest rock on Earth?": "Diamond",
    "Who was the first man to walk on the moon?": "Neil Armstrong",
    "Which bird is a symbol of peace?": "Dove",
    "Which planet has the most moons?": "Saturn",
    "What is the national sport of Canada?": "Ice Hockey",
    "Who wrote 'The Odyssey'?": "Homer",
    "Which part of the plant conducts photosynthesis?": "Leaves",
    "What is the largest organ in the human body?": "Skin",
    "What is the national flower of the Netherlands?": "Tulip",
    "What is the only planet not named after a god?": "Earth",
    "Which country hosted the 2016 Summer Olympics?": "Brazil",
    "What is the smallest country in Europe?": "Vatican City",
    "What is the boiling point of water in Fahrenheit?": "212",
    "Which metal is liquid at room temperature?": "Mercury",
    "What is the capital of South Korea?": "Seoul",
    "What is the square root of 144?": "12",
    "Which sea is the saltiest in the world?": "Dead Sea",
    "What is the deepest point in Earth's oceans?": "Mariana Trench",
    "What is the smallest particle of an element?": "Atom",
    "What is the national dish of Italy?": "Pizza",
    "Who discovered penicillin?": "Alexander Fleming",
    "What is the freezing point of water (°C)?": "0",
    "Which animal is known as the King of the Jungle?": "Lion",
    "Which planet is closest to the Sun?": "Mercury",
    "What is the largest continent by area?": "Asia",
    "Which gas is essential for human respiration?": "Oxygen",
    "What is the most famous prehistoric monument in the UK?": "Stonehenge",
}
